import "~/styles/globals.css";
import {ClerkProvider} from '@clerk/nextjs';
import { Inter } from "next/font/google";
import "@uploadthing/react/styles.css";
import { Toaster } from "sonner";

import {TopNav} from './_components/topnav';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import React from "react";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by Kausthubh Konuru",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
    <NextSSRPlugin
      
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <body className={`font-sans ${inter.variable} dark`}>
      <TopNav/>
        <div className="h-screen grid gird-rows-[auto,1fr]">
        <main className="overflow y-scroll">{children}</main>
        {modal}
        <div id="modal-root" />
        <Toaster />
        </div>
        </body>
    </html>
    </ClerkProvider>
  );
}
